name: flutter_login_demo
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7

  # cupertino_icons: ^0.1.3
  image_sequence_animator:
    git:
      url: 'https://github.com/papmodern/flutter-image-sequence-animator.git'
      path: 'image_sequence_animator'


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/flutter-icon.png
    - assets/guitarSequence/
